expose_php = Off
display_errors = Off
log_errors = On
error_log = /dev/stderr
allow_url_include = Off
open_basedir = /srv/privatebin:/data:/tmp:/etc/ssl
memory_limit = 128M
upload_max_filesize = 16M
post_max_size = 16M
max_execution_time = 30
session.use_strict_mode = 1
session.cookie_httponly = 1
session.cookie_samesite = Lax
opcache.enable = 1
opcache.validate_timestamps = 0
opcache.memory_consumption = 64
